# Generated by Django 5.1.7 on 2025-04-08 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='file',
            field=models.FileField(default='', upload_to='vendor_contracts/'),
            preserve_default=False,
        ),
    ]
