# Generated by Django 5.1.7 on 2025-04-09 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_document_updated_at_alter_document_document_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('citizenship_front', 'Citizenship Front'), ('citizenship_back', 'Citizenship Back'), ('bank_details', 'Bank Details'), ('pan_card', 'PAN Card'), ('other', 'Other')], max_length=50),
        ),
    ]
